# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export HISTSIZE=20000
export HISTFILESIZE=20000
export PS1="\[[1m[96m\]EP_Dev_Env\[[0m\]=>[\W]>"

EP_SCR_DIR="/home/$USER/ep_dev_env/scripts";

alias rel='bash $EP_SCR_DIR/EP_rel';
alias log='bash $EP_SCR_DIR/EP_log';
alias list='bash $EP_SCR_DIR/EP_list';
#to be fixed!
alias build='bash $EP_SCR_DIR/../repo_builder.sh';
alias go='. $EP_SCR_DIR/EP_goto';
