#! /usr/bin/bash

# deletes the repository and all of its contents

if [[ $# -eq 0 ]]; then
	echo '[1;37m---------------------';
	printf "\n[1m[31mYou must specify which repo you want to delete. [0m \n
    So something like: EP_static [repo ID]\n";
	bash /home/$USER/ep_dev_env/scripts/EP_list;	
	echo '[1;37m---------------------[0m';
	exit 0;
fi

export EP_ID=$1;
DIR="/home/$USER/eprints/$EP_ID";

#Checks if the repo exists or not
#===================================================
EP_DIR=/home/$USER/eprints;
REPO_EXISTS=0;

if [ -d $EP_DIR ]; then 
	for repo in $EP_DIR/*; do
		[[ $repo =~ eprints\/$EP_ID$ ]] && REPO_EXISTS=1;	
	done
fi

if [ $REPO_EXISTS -eq 1 ] && [ $EP_ID != 'templates' ]; then
        printf "[93m\nHooray! The repo exists!\n\n[96m[1mDELETING $EP_ID...\n\n[0m";

else
    echo '[1;37m---------------------';
            printf "[1m[31mThe \'$EP_ID\' repository is not installed![0m";
            bash /home/$USER/ep_dev_env/scripts/EP_list;
            printf "\n[1;37mTo install a new repo, run EP_repo_build.[0m\nExiting reload....\n";
            echo '[1;37m---------------------';
            exit 0;

fi 
#====================================================

rm -rf $DIR;
mysql <<< "drop database $EP_ID"

printf "\n[1m[93m'$EP_ID' was destroyed!!![0m\n\n";
