#! /usr/bin/bash

# regenerates the static of the repo. 

if [[ $# -eq 0 ]]; then
	echo '[1;37m---------------------';
	printf "\n[1m[31mYou must specify which repo you want to generate the static. [0m \nSo something like: EP_static [repo ID]\n";
	bash /home/$USER/ep_dev_env/scripts/EP_list;	
	echo '[1;37m---------------------[0m';
	exit 0;
fi

export EP_ID=$1;
DIR="/home/$USER/eprints/$EP_ID/eprints3/bin";

#Checks if the repo exists or not
#===================================================
EP_DIR=/home/$USER/eprints;
REPO_EXISTS=0;

if [ -d $EP_DIR ]; then 
	for repo in $EP_DIR/*; do
		if [[ $repo =~ eprints\/$EP_ID$ ]]; then
                REPO_EXISTS=1;
    fi	
	done
fi

if [ $REPO_EXISTS -eq 1 ] && [ $EP_ID != 'templates' ]; then
        printf "[93m\nHooray! The repo exists!\n\n[96m[1mINITIATING THE GENERATION OF THE STATIC FOR $EP_ID...\n\n[0m";

else
    echo '[1;37m---------------------';
            printf "[1m[31mThe \'$EP_ID\' repository is not installed![0m";
            bash /home/$USER/ep_dev_env/scripts/EP_list;
            printf "\n[1;37mTo install a new repo, run EP_repo_build.[0m\nExiting reload....\n";
            echo '[1;37m---------------------';
            exit 0;

fi 
#====================================================

#EP command - reload the repo
$DIR/generate_static $EP_ID;

printf "\n[1m[93mSTATIC GENERATED!![0m\nNow you can check [96mlocalhost:8080[0m on your host...\n\n";
